change yml2

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -54,6 +54,14 @@ jobs:
          git fetch origin main || true
          git fetch origin feature/update-message || true
          git diff origin/main...feature/update-message || echo "Diff generation skipped due to missing branch"
+      - run: |
+         git fetch origin main || true
+         git fetch origin feature/update-message || true
+            if git rev-parse --verify origin/feature/update-message >/dev/null 2>&1; then
+         git diff origin/main...origin/feature/update-message
+         else
+          echo "Diff generation skipped: feature/update-message branch not found."
+         fi
       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
